Parameters:
  TableName:
    Description: 'The name of the DynamoDB table'
    Type: String

Resources:
  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: date
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Ref TableName

Outputs:
  DynamoDBTableName:
    Description: 'The name of the DynamoDB table'
    Value: !Ref TableName
    Export:
      Name: !Sub "${AWS::StackName}-${TableName}"
